### ISSUE TITLE
Yeoman Doesn't Show any entity when we try to use Ui5 SpreadsheetImporter

### ISSUE THREAD

**Issue by jaydeepgirigoswami** [marianfoo/ui5-cc-spreadsheetimporter#453]
Hello Team,

First of all thanks for all the descriptive and amazing blog on how to import SpreadSheet code within minutes.

But unfortunately i am facing an issue while importing Spreadsheet using Yeoman Generator.

I have used a standard way of creating a CAPM Model based FIORI application using the Link Provided below:
https://blogs.sap.com/2023/06/07/create-and-deploy-a-cap-application-with-fiori-ui-in-minutes/

Once that is done i Use the YO Generator to add the spreadsheet code but unfortunately the Entity on which i need the spreadsheet is not being displayed in the terminal.
Please find below the screenshot. 

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/149174643/e4a30a6d-246d-436a-bb19-0a96cdb534db)

Could you please help me identify the issue?

**Comment by jaydeepgirigoswami** [comment]
Hello Marian,

Sorry to bother you but I have used the same link mentioned by you, 

Also i have imported the whole code from: https://github.com/marianfoo/spreadsheetimporter-btp-example.git. (To check what went wrong )

But even that doesn't seem to work, when i click on SpreadsheetUpload button it provides below error: 

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/149174643/ee824869-f423-442c-b06a-5edc8425b8c7)

I'm not sure how to move futher and am stuck with a dead end. Could you please shed some light if possible, it would be of great help.

**Comment by marianfoo** [comment]
I added a new commit that should fix that
https://github.com/marianfoo/spreadsheetimporter-btp-example/commit/c4ee947042620241a049b73f6f5e5745bf2cec89

**Comment by jaydeepgirigoswami** [comment]
Thanks a ton @marianfoo for looking into it, it means a lot.

The Application is now working in the BAS local system after your change, also I was able to deploy the application on CF without any errors but when i launch the application on CF it gives the same error as below. 

Hope to hear from you soon !!!!

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/149174643/2c57bd72-b206-41d1-8868-b38633c5b21a)

I have also added below code in manifest file as per the blog: https://docs.spreadsheet-importer.com/pages/GettingStarted/

"sap.app": {
  "embeds": ["thirdparty/customControl/spreadsheetImporter/v0_29_0"]
}

But no luck.
Any idea what might have gone wrong?  ( P.S: So sorry to bug you with this )

**Comment by marianfoo** [comment]
Hi @jaydeepgirigoswami 
great to hear.
I saw that you wrote earlier it did not work.
What was the fix?

**Comment by jaydeepgirigoswami** [comment]
Hello Marian,

Yes, i somehow missed the Spreadsheet Importer dependancy in ui5-deploy.yaml file, I compare the files with your Application and added it in mine.

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/149174643/d56ec47b-9497-423a-b92b-f7d575354172)




**Quick Question if you are available:** 

I was still not able to acheive the same developement via Yo generator ( https://docs.spreadsheet-importer.com/pages/Generator/ ).

I had to manually perform the steps mentioned in the blog ( Added button using Guided Dev and Added Spreadsheet importer in manifest and package.json file ) ( https://docs.spreadsheet-importer.com/pages/GettingStarted/ ).

Everytime i use the Yo genertor it asks for the Entity set, but no entity was available to select. 

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/149174643/9735aaf4-bcb3-417d-94e7-58c77db01169)

I also saw you video  (  https://www.youtube.com/watch?v=dODt9ZWmi4A&t=79s ) which i follwed but same issue.

Is there an issue with the generator or i am doing something wrong ?

**Comment by marianfoo** [comment]
Yeah, i stopped developing it because i dont like the generator and the setting up is simple and i dont want to recreate the Guiding Development Extension from SAP.
https://github.com/marianfoo/ui5-cc-spreadsheetimporter/issues/245

**Comment by jaydeepgirigoswami** [comment]
oh ok, Got it, then i won't try to develop the app via generator now, i was going to try the generator in some different ways to know more about it.

Anyways, thanks a lot for the information and quick reply.

Have a good day !!!!
